version: '3.3'

services:
        app:
                container_name: productservice_v1
                build:
                        context: .
                        dockerfile: Dockerfile
                restart: always
                ports:
                        - "64421:64421"
