server:
  port: 64421

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-instance-for-1-products.cpae2i8tmjoo.ap-northeast-2.rds.amazonaws.com:3306/productdb?useSSL=FALSE&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        search:
          enabled: true
          backend:
            type: lucene
            directory.root: ./data/index
  redis:
    host: redis
    port: 6379

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 60
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://a9630be5aa11c4d0a8ae29e80ddf7437-1705600513.ap-northeast-2.elb.amazonaws.com:8761/eureka

prefix:
  key: recents

discount:
  public: 30
  select12: 25
  select24: 25
