-- MySQL Script generated by MySQL Workbench
-- Sat Jul 23 23:17:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema productdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema productdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `productdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `productdb` ;

-- -----------------------------------------------------
-- Table `productdb`.`phone_brand_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productdb`.`phone_brand_category` ;

CREATE TABLE IF NOT EXISTS `productdb`.`phone_brand_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unq_phone_brand_category_on_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `productdb`.`phone_storage_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productdb`.`phone_storage_category` ;

CREATE TABLE IF NOT EXISTS `productdb`.`phone_storage_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capability` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unq_phone_storage_category_on_capability` (`capability` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `productdb`.`phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productdb`.`phone` ;

CREATE TABLE IF NOT EXISTS `productdb`.`phone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `storage_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `img_thumbnail` VARCHAR(255) NOT NULL,
  `network_support` VARCHAR(10) NOT NULL,
  `discount_type` INT NULL DEFAULT NULL,
  `color` VARCHAR(20) NOT NULL,
  `color_hex_code` VARCHAR(20) NOT NULL,
  `price` INT NOT NULL,
  `sales` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unq_phone_on_code_and_color` (`code` ASC, `color` ASC) VISIBLE,
  INDEX `fk_phone_phone_storage_category1_idx` (`storage_id` ASC) VISIBLE,
  INDEX `fk_phone_phone_brand_category1_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `fk_phone_phone_brand_category1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `productdb`.`phone_brand_category` (`id`),
  CONSTRAINT `fk_phone_phone_storage_category1`
    FOREIGN KEY (`storage_id`)
    REFERENCES `productdb`.`phone_storage_category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `productdb`.`phone_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productdb`.`phone_image` ;

CREATE TABLE IF NOT EXISTS `productdb`.`phone_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone_id` INT NOT NULL,
  `img_path` VARCHAR(255) NOT NULL,
  `img_name` VARCHAR(50) NOT NULL,
  `img_pos` VARCHAR(30) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `img_color` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unq_phone_image_on_img_name_and_img_pos_and_img_color` (`img_name` ASC, `img_pos` ASC, `img_color` ASC) VISIBLE,
  INDEX `fk_phone_image_phone1_idx` (`phone_id` ASC) VISIBLE,
  CONSTRAINT `fk_phone_image_phone1`
    FOREIGN KEY (`phone_id`)
    REFERENCES `productdb`.`phone` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `productdb`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productdb`.`plan` ;

CREATE TABLE IF NOT EXISTS `productdb`.`plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) NOT NULL,
  `network_support` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `data` INT NOT NULL,
  `message` INT NOT NULL,
  `voice` INT NOT NULL,
  `price` INT NOT NULL,
  `share_data` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unq_plan_on_code` (`code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
